base.url=https://automationexercise.com
endpoint.products=/api/productsList
endpoint.brands=/api/brandsList
endpoint.searchProduct=/api/searchProduct
search.product.term=top
search.product.key=search_product

api.ok.status=200
api.method.not.allowed.status=405
api.not.supported.message=This request method is not supported.

log.file.path=target/test-logs/api-test.log
